### ISSUE TITLE
Bootloop on Google Pixel

### ISSUE THREAD

**Issue by MarcAnt01** [Magisk-Modules-Repo/Oxy-ify#12]
All the Pixel devices are stuck in bootloop after Oxy-ify installation, if anyone is wishing to help me to solve that ping me in the Telegram group

**Comment by samsapti** [comment]
The same happens OnePlus 5T on LineageOS. Since TWRP cannot decrypt /data on LineageOS, I couldn't even remove the module from magisk recovery manager, so I had to reflash everything.

**Comment by MarcAnt01** [comment]
> The same happens OnePlus 5T on LineageOS. Since TWRP cannot decrypt /data on LineageOS, I couldn't even remove the module from magisk recovery manager, so I had to reflash everything.

I'm rewriting Oxy-ify from scratch, so these bugs will probably be gone👍

**Comment by MarcAnt01** [comment]
This is fixed now
